package de.comline.rules;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

rule "Flow-Control"
salience 1000
when
then
    kcontext.getKnowledgeRuntime().getAgenda().getAgendaGroup("init").setFocus();
end


global List<String> $List;

rule "init"
agenda-group "init"
when
then
    kcontext.getKieRuntime().setGlobal("$List", Arrays.asList("bar","baz"));
end


rule "use global list"
when
    $exists: Boolean(this == true) from ($List contains "bar")
then
    System.out.println("exists: " + $exists);
end
